param(
    [Parameter(Mandatory = $true)]
    [string]$Version,

    [Parameter(Mandatory = $true)]
    [string]$BaseReleaseZip
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot

function Assert-PackagingBatchFile([string]$Path) {
    $bytes = [System.IO.File]::ReadAllBytes($Path)
    if ($bytes.Length -ge 3 -and $bytes[0] -eq 0xEF -and $bytes[1] -eq 0xBB -and $bytes[2] -eq 0xBF) {
        throw "Packaging BAT must not contain a UTF-8 BOM: $Path"
    }
    $text = [System.Text.Encoding]::ASCII.GetString($bytes)
    if ($text -notmatch 'echo "%TARGET%"') {
        throw "Packaging BAT does not quote TARGET path output: $Path"
    }
}

$BaseReleaseZip = [System.IO.Path]::GetFullPath($BaseReleaseZip)

if (-not (Test-Path -LiteralPath $BaseReleaseZip -PathType Leaf)) {
    throw "Base release ZIP was not found: $BaseReleaseZip"
}

$SafeVersion = $Version -replace '[^0-9A-Za-z._-]', '_'
$DistRoot = Join-Path $RepoRoot 'dist'
$StageName = "RO3_Asia_Thai_Patch_$SafeVersion"
$Stage = Join-Path $DistRoot $StageName
$Zip = Join-Path $DistRoot ($StageName + '.zip')
$ShaFile = Join-Path $DistRoot ($StageName + '.sha256.txt')
$TempRoot = Join-Path ([System.IO.Path]::GetTempPath()) (
    'RO3_Release_Base_' + [Guid]::NewGuid().ToString('N'))
$ExtractRoot = Join-Path $TempRoot 'extracted'

$runtimeFiles = @(
    '.doorstop_version',
    'doorstop_config.ini',
    'winhttp.dll',
    'BepInEx\config\BepInEx.cfg',
    'BepInEx\config\gravydevsupreme.xunity.resourceredirector.cfg',
    'BepInEx\core\0Harmony.dll',
    'BepInEx\core\0Harmony20.dll',
    'BepInEx\core\BepInEx.dll',
    'BepInEx\core\BepInEx.Harmony.dll',
    'BepInEx\core\BepInEx.Preloader.dll',
    'BepInEx\core\HarmonyXInterop.dll',
    'BepInEx\core\Mono.Cecil.dll',
    'BepInEx\core\Mono.Cecil.Mdb.dll',
    'BepInEx\core\Mono.Cecil.Pdb.dll',
    'BepInEx\core\Mono.Cecil.Rocks.dll',
    'BepInEx\core\MonoMod.RuntimeDetour.dll',
    'BepInEx\core\MonoMod.Utils.dll',
    'BepInEx\core\XUnity.Common.dll',
    'BepInEx\plugins\XUnity.AutoTranslator\ExIni.dll',
    'BepInEx\plugins\XUnity.AutoTranslator\XUnity.AutoTranslator.Plugin.BepInEx.dll',
    'BepInEx\plugins\XUnity.AutoTranslator\XUnity.AutoTranslator.Plugin.Core.dll',
    'BepInEx\plugins\XUnity.AutoTranslator\XUnity.AutoTranslator.Plugin.ExtProtocol.dll',
    'BepInEx\plugins\XUnity.ResourceRedirector\XUnity.ResourceRedirector.BepInEx.dll',
    'BepInEx\plugins\XUnity.ResourceRedirector\XUnity.ResourceRedirector.dll'
)

$repoPayloadFiles = @(
    'arialuni_sdf_u2022',
    'BepInEx\config\AutoTranslatorConfig.ini',
    'BepInEx\config\RO3.LocalizationOverrides.tsv',
    'BepInEx\config\RO3.LocalizationAliases.tsv',
    'BepInEx\plugins\RO3.LocalizationTablePatcher.dll',
    'BepInEx\Translation\ja\Text\_AutoGeneratedTranslations.txt',
    'BepInEx\Translation\ja\Text\RO3_CanonicalTranslations.txt',
    'BepInEx\Translation\ja\Text\RO3_PriorityOverrides.txt',
    'BepInEx\Translation\ja\Text\RO3_RuntimePlaceholders.txt'
)

$forbiddenPayloadFiles = @(
    'BepInEx\plugins\RO3WorldNameplateProbe.dll',
    'BepInEx\plugins\RO3.LuaNameplateModuleInspector.dll',
    'BepInEx\plugins\RO3.WorldNameTranslator.dll',
    'BepInEx\config\RO3.WorldNameTranslations.tsv'
)

New-Item -ItemType Directory -Path $ExtractRoot -Force | Out-Null
try {
    Expand-Archive -LiteralPath $BaseReleaseZip -DestinationPath $ExtractRoot -Force

    $BasePayloads = @(
        Get-ChildItem -LiteralPath $ExtractRoot -Recurse -Directory -Filter 'payload' |
            Where-Object {
                Test-Path -LiteralPath (Join-Path $_.FullName 'BepInEx\core\BepInEx.dll') -PathType Leaf
            }
    )
    if ($BasePayloads.Count -ne 1) {
        throw "Expected exactly one release payload in base ZIP, found $($BasePayloads.Count)."
    }

    New-Item -ItemType Directory -Path $DistRoot -Force | Out-Null
    if (Test-Path -LiteralPath $Stage) { Remove-Item -LiteralPath $Stage -Recurse -Force }
    if (Test-Path -LiteralPath $Zip) { Remove-Item -LiteralPath $Zip -Force }
    if (Test-Path -LiteralPath $ShaFile) { Remove-Item -LiteralPath $ShaFile -Force }
    New-Item -ItemType Directory -Path (Join-Path $Stage 'payload') -Force | Out-Null

    foreach ($relative in $runtimeFiles) {
        $source = Join-Path $BasePayloads[0].FullName $relative
        if (-not (Test-Path -LiteralPath $source -PathType Leaf)) {
            throw "Required inherited runtime file is missing from base release: $relative"
        }
        $destination = Join-Path (Join-Path $Stage 'payload') $relative
        New-Item -ItemType Directory -Path (Split-Path -Parent $destination) -Force | Out-Null
        Copy-Item -LiteralPath $source -Destination $destination -Force
    }

    $rootFiles = @(
        'Install-Thai.bat',
        'Update-Thai.bat',
        'Update-Latest.ps1',
        'Uninstall-Thai.bat',
        'Restore-Recovery.ps1',
        'Recover-Thai.bat',
        'Recover-After-Official-Repair.bat',
        'README.txt'
    )
    foreach ($name in $rootFiles) {
        $source = Join-Path $RepoRoot (Join-Path 'packaging' $name)
        if (-not (Test-Path -LiteralPath $source -PathType Leaf)) {
            throw "Required packaging file is missing: $source"
        }
        Copy-Item -LiteralPath $source -Destination $Stage -Force
    }
    Assert-PackagingBatchFile (Join-Path $Stage 'Install-Thai.bat')
    Assert-PackagingBatchFile (Join-Path $Stage 'Uninstall-Thai.bat')

    Copy-Item -LiteralPath (Join-Path $RepoRoot 'THIRD_PARTY_NOTICES.md') -Destination $Stage -Force
    New-Item -ItemType Directory -Path (Join-Path $Stage 'licenses') -Force | Out-Null
    Copy-Item -LiteralPath (Join-Path $RepoRoot 'third_party\BepInEx-LICENSE.txt') `
        -Destination (Join-Path $Stage 'licenses\BepInEx-LICENSE.txt') -Force
    Copy-Item -LiteralPath (Join-Path $RepoRoot 'third_party\XUnity-AutoTranslator-LICENSE.txt') `
        -Destination (Join-Path $Stage 'licenses\XUnity-AutoTranslator-LICENSE.txt') -Force
    Set-Content -LiteralPath (Join-Path $Stage 'VERSION.txt') -Value $Version -Encoding ASCII

    # Include the offline hand-translation editor for contributors.
    Copy-Item -LiteralPath (Join-Path $RepoRoot 'Translation-Editor') `
        -Destination (Join-Path $Stage 'Translation-Editor') -Recurse -Force

    foreach ($relative in $repoPayloadFiles) {
        $source = Join-Path (Join-Path $RepoRoot 'Client') $relative
        if (-not (Test-Path -LiteralPath $source -PathType Leaf)) {
            throw "Repository payload file is missing: $source"
        }
        $destination = Join-Path (Join-Path $Stage 'payload') $relative
        New-Item -ItemType Directory -Path (Split-Path -Parent $destination) -Force | Out-Null
        Copy-Item -LiteralPath $source -Destination $destination -Force
        $sourceHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $source).Hash
        $destinationHash = (Get-FileHash -Algorithm SHA256 -LiteralPath $destination).Hash
        if ($sourceHash -ne $destinationHash) {
            throw "Repository payload copy mismatch: $relative"
        }
    }

    $stageCanonical = Join-Path $Stage 'payload\BepInEx\Translation\ja\Text\RO3_CanonicalTranslations.txt'
    $stageOverrides = Join-Path $Stage 'payload\BepInEx\config\RO3.LocalizationOverrides.tsv'
    $canonicalText = Get-Content -LiteralPath $stageCanonical -Raw
    if ($canonicalText -notmatch '(?m)^ST=Single Target\r?$') {
        throw 'Release payload is missing ST=Single Target.'
    }
    $falconRow = Get-Content -LiteralPath $stageOverrides | Where-Object {
        $_.StartsWith("10110300401`t")
    } | Select-Object -First 1
    if (-not $falconRow -or -not $falconRow.Contains('Single Target') -or -not $falconRow.Contains('P.ATK')) {
        throw 'Release payload is missing the reviewed Falcon Concentration translation.'
    }

    foreach ($relative in $forbiddenPayloadFiles) {
        $path = Join-Path (Join-Path $Stage 'payload') $relative
        if (Test-Path -LiteralPath $path) {
            throw "Forbidden diagnostic/deprecated file unexpectedly present in release payload: $path"
        }
    }

    Compress-Archive -LiteralPath $Stage -DestinationPath $Zip -CompressionLevel Optimal
    $Hash = (Get-FileHash -Algorithm SHA256 -LiteralPath $Zip).Hash.ToUpperInvariant()
    Set-Content -LiteralPath $ShaFile `
        -Value ($Hash + '  ' + [System.IO.Path]::GetFileName($Zip)) `
        -Encoding ASCII

    Write-Host ''
    Write-Host '[OK] CI release package created'
    Write-Host "     Version: $Version"
    Write-Host "     Base:    $BaseReleaseZip"
    Write-Host "     ZIP:     $Zip"
    Write-Host "     SHA256:  $Hash"
    Write-Host "     SHA file:$ShaFile"
}
finally {
    if (Test-Path -LiteralPath $TempRoot) {
        Remove-Item -LiteralPath $TempRoot -Recurse -Force -ErrorAction SilentlyContinue
    }
}
