param(
    [Parameter(Mandatory = $true)] [ValidatePattern('^[0-9.]+$')] [string]$Version,
    [switch]$EnableTrace,
    [ValidatePattern('^display-[0-9.]+-[a-f0-9]{32}$')] [string]$ResumeBackupName
)
$ErrorActionPreference = 'Stop'
$repo = Split-Path -Parent $PSScriptRoot
$gameRoot = Split-Path -Parent $repo
$client = Join-Path $gameRoot 'Client'
$exe = Join-Path $client 'ro3.exe'
if (@(Get-Process ro3 -ErrorAction SilentlyContinue | Where-Object { $_.Path -ieq $exe }).Count) {
    throw 'Close the game normally before applying the audited build.'
}
$payload = @(
    'BepInEx\plugins\RO3.LocalizationTablePatcher.dll',
    'BepInEx\config\RO3.LocalizationOverrides.tsv',
    'BepInEx\config\RO3.LocalizationAliases.tsv',
    'BepInEx\Translation\ja\Text\RO3_CanonicalTranslations.txt',
    'BepInEx\Translation\ja\Text\RO3_PriorityOverrides.txt',
    'BepInEx\Translation\ja\Text\RO3_RuntimePlaceholders.txt',
    'BepInEx\Translation\ja\Text\_AutoGeneratedTranslations.txt'
)
$protected = @(
    'BepInEx\config\AutoTranslatorConfig.ini',
    'ro3_Data\StreamingAssets\Recovery\recovery-compatibility-manifest.json',
    'ro3_Data\StreamingAssets\Recovery\recovery-compatibility-manifest.json.sig',
    'ro3_Data\StreamingAssets\Recovery\LuaPayload\Localization_en.lua.bytes',
    'ro3_Data\StreamingAssets\Recovery\LuaPayload\Localization_zh_CN.lua.bytes',
    'ro3_Data\StreamingAssets\Recovery\LuaPayload\Localization_zh_TW.lua.bytes'
)
$before = @{}
foreach ($relative in $protected) { $before[$relative] = (Get-FileHash -LiteralPath (Join-Path $client $relative)).Hash }
# Validate the UTF-8 fixture before copying anything. Keep script source ASCII
# because Windows PowerShell 5.1 decodes BOM-less scripts with the ANSI codepage.
$fixtureRelative = 'BepInEx\config\RO3.DisplayRegressionChecks.tsv'
$traceRelative = 'BepInEx\config\RO3.DisplayTrace.enable'
$fixture = @([IO.File]::ReadAllLines((Join-Path $PSScriptRoot 'history-regression-cases.tsv')) | Where-Object {
    (-not $_.StartsWith('world-') -and -not $_.StartsWith('template-history:') -and -not $_.StartsWith('canonical-template:') -and -not $_.StartsWith('canonical-literal:')) -or $_ -match '\t(?:\u866b\u86f9|\u87f2\u86f9|\u5409\u82ac|\u6590|\u4e0b\u6c34\u9053)'
})
if ($fixture.Count -lt 268) { throw 'Incomplete display regression fixture.' }
foreach ($relative in $payload) {
    if (-not (Test-Path -LiteralPath (Join-Path (Join-Path $repo 'Client') $relative) -PathType Leaf)) {
        throw "Missing generated payload: $relative"
    }
}
if ($ResumeBackupName) {
    $backup = Join-Path $gameRoot ('_TranslationWorkspace\deploy-backups\' + $ResumeBackupName)
    if (-not (Test-Path -LiteralPath (Join-Path $backup 'BepInEx\plugins\RO3.LocalizationTablePatcher.dll'))) {
        throw 'Existing backup was not found; refusing to replace it.'
    }
} else {
    $backup = Join-Path $gameRoot ('_TranslationWorkspace\deploy-backups\display-' + $Version + '-' + [Guid]::NewGuid().ToString('N'))
    New-Item -ItemType Directory -Path $backup -Force | Out-Null
    $before | ConvertTo-Json | Set-Content -LiteralPath (Join-Path $backup 'protected-before.json') -Encoding UTF8
    foreach ($relative in @($payload) + @($fixtureRelative, $traceRelative)) {
        $installed = Join-Path $client $relative
        if (Test-Path -LiteralPath $installed -PathType Leaf) {
            $saved = Join-Path $backup $relative
            New-Item -ItemType Directory -Path (Split-Path -Parent $saved) -Force | Out-Null
            Copy-Item -LiteralPath $installed -Destination $saved
        }
    }
}
foreach ($relative in $payload) {
    $source = Join-Path (Join-Path $repo 'Client') $relative
    $target = Join-Path $client $relative
    if (-not $ResumeBackupName) { Copy-Item -LiteralPath $source -Destination $target -Force }
    if ((Get-FileHash -LiteralPath $source).Hash -ne (Get-FileHash -LiteralPath $target).Hash) {
        throw "Deployment hash mismatch: $relative"
    }
}
[IO.File]::WriteAllLines((Join-Path $client $fixtureRelative), $fixture, (New-Object Text.UTF8Encoding($false)))
if ($EnableTrace) { [IO.File]::WriteAllText((Join-Path $client $traceRelative), 'Developer display audit') }
foreach ($relative in $protected) {
    if ($before[$relative] -ne (Get-FileHash -LiteralPath (Join-Path $client $relative)).Hash) {
        throw "Protected file changed: $relative"
    }
}
$record = @{ version = $Version; protected_sha256 = $before; payload = $payload; live_cases = $fixture.Count; resumed = [bool]$ResumeBackupName }
$record | ConvertTo-Json -Depth 4 | Set-Content -LiteralPath (Join-Path $backup 'audit.json') -Encoding UTF8
Write-Output "Applied $($payload.Count) files; all hashes match. Protected files unchanged: $($protected.Count). Live cases: $($fixture.Count)."
Write-Output "Backup: $backup"
