param(
    [Parameter(Mandatory = $false)]
    [string]$GameRoot
)

$ErrorActionPreference = 'Stop'
$RepoRoot = Split-Path -Parent $PSScriptRoot

if ([string]::IsNullOrWhiteSpace($GameRoot)) {
    # Default for the current checkout location:
    # <RO3 Asia Launcher>\RO3_Asia_Japanese_Patch
    $GameRoot = Split-Path -Parent $RepoRoot
}

$GameRoot = [System.IO.Path]::GetFullPath($GameRoot)
$TargetClient = Join-Path $GameRoot 'Client'
$GameExe = Join-Path $TargetClient 'ro3.exe'

if (-not (Test-Path -LiteralPath $GameExe -PathType Leaf)) {
    throw "ro3.exe was not found at: $GameExe"
}

$runningGame = Get-CimInstance Win32_Process -Filter "Name='ro3.exe'" |
    Where-Object {
        $_.ExecutablePath -and
        [string]::Equals(
            [System.IO.Path]::GetFullPath($_.ExecutablePath),
            $GameExe,
            [System.StringComparison]::OrdinalIgnoreCase)
    }
if ($runningGame) {
    throw "RO3 is currently running. Close the game before deploying so the payload cannot be copied partially."
}

$SourceClient = Join-Path $RepoRoot 'Client'
$files = @(
    'BepInEx\Translation\ja\Text\_AutoGeneratedTranslations.txt',
    'BepInEx\Translation\ja\Text\RO3_CanonicalTranslations.txt',
    'BepInEx\Translation\ja\Text\RO3_PriorityOverrides.txt',
    'BepInEx\Translation\ja\Text\RO3_RuntimePlaceholders.txt',
    'BepInEx\config\AutoTranslatorConfig.ini',
    'BepInEx\config\RO3.LocalizationOverrides.tsv',
    'BepInEx\config\RO3.LocalizationAliases.tsv',
    'BepInEx\plugins\RO3.LocalizationTablePatcher.dll',
    'arialuni_sdf_u2022'
)

foreach ($relative in $files) {
    $source = Join-Path $SourceClient $relative
    if (-not (Test-Path -LiteralPath $source -PathType Leaf)) {
        throw "Repository payload file is missing: $source"
    }
}

foreach ($relative in $files) {
    $source = Join-Path $SourceClient $relative
    $destination = Join-Path $TargetClient $relative
    $destinationDir = Split-Path -Parent $destination
    New-Item -ItemType Directory -Path $destinationDir -Force | Out-Null
    Copy-Item -LiteralPath $source -Destination $destination -Force
    Write-Host "[COPIED] $relative"
}

# Remove obsolete development implementations after the replacement has been
# copied successfully. These files were never part of the public v2026.09.17.1
# release, but may exist in a developer/test installation.
$obsoleteFiles = @(
    'BepInEx\config\RO3.WorldNameTranslations.tsv',
    'BepInEx\plugins\RO3.WorldNameTranslator.dll',
    'BepInEx\plugins\RO3.LuaNameplateModuleInspector.dll'
)
foreach ($relative in $obsoleteFiles) {
    $path = Join-Path $TargetClient $relative
    if (Test-Path -LiteralPath $path -PathType Leaf) {
        Remove-Item -LiteralPath $path -Force
        Write-Host "[REMOVED obsolete] $relative"
    }
}

Write-Host ""
Write-Host "[OK] Japanese translation payload deployed to: $TargetClient"
Write-Host "     Restart RO3 to load the localization-table patcher DLL."
