#!/usr/bin/env python3
"""Normalize approved mixed Thai/English combat terminology across the payload."""

from __future__ import annotations

import csv
import io
import re
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
WORKSPACE = ROOT / "_TranslationWorkspace"
SPLIT = WORKSPACE / "split_1000"
LANGUAGE_KV = WORKSPACE / "LanguageKV_full_en.tsv"
OVERRIDES = ROOT / "Client/BepInEx/config/RO3.LocalizationOverrides.tsv"
TEXT = ROOT / "Client/BepInEx/Translation/ja/Text"
CANON = TEXT / "RO3_CanonicalTranslations.txt"
AUTO = TEXT / "_AutoGeneratedTranslations.txt"

ALLOWED_PREFIXES = (
    "101103",
    "102203",
    "108001",
    "123901",
    "100501",
    "131500",
    "131502",
    "131506",
)

FALCON_CONCENTRATION = (
    "Can only be cast while the Falcon is in Follow mode. Use the Falcon to "
    "perform Concentration, dealing PATK * ^{1}${2}% + ${3}^{2} Neutral "
    "Ranged Physical DMG to the designated ST enemy within ${1} meters."
)
FALCON_CONCENTRATION_TH = (
    "ใช้ได้เฉพาะเมื่อ Falcon อยู่ใน Follow Mode เท่านั้น สั่ง Falcon ให้ทำการ "
    "Concentration สร้าง Neutral P.DMG ระยะไกลเท่ากับ P.ATK * "
    "^{1}${2}% + ${3}^{2} แก่ศัตรูแบบ Single Target ที่กำหนดภายในระยะ "
    "${1} เมตร"
)
MALFORMED_POISONED = (
    "Plant timed Dynamite on a designated ST enemy within ${1} meters. After "
    "${2} seconds, deal Physical ATK * ^{1}${5}%^{2} Poison ranged Physical "
    "damage that ignores FLEE to the designated enemy and up to ${4} other "
    "enemies within a ${3}-meter radius, and inflict "
    "【^{3}^{4}【Poisoned】^{5}^{6} damage on the target."
)
MALFORMED_POISONED_TH = (
    "วาง Timed Dynamite บนศัตรูแบบ Single Target ที่กำหนดภายในระยะ ${1} เมตร "
    "หลังจาก ${2} วินาที จะสร้าง Poison P.DMG ระยะไกลเท่ากับ P.ATK * "
    "^{1}${5}%^{2} โดย Ignore Flee แก่ศัตรูที่กำหนดและศัตรูอื่นสูงสุด ${4} ตัว"
    "ภายในรัศมี ${3} เมตร พร้อมทำให้เป้าหมายได้รับ "
    "^{3}^{4}[ Poisoned ]^{5}^{6}"
)

PROTECTED_NAME = re.compile(r"(\[[^\]\r\n]+\]|【[^】\r\n]+】|<[^>\r\n]+>)")

RULES = [
    ("ST", re.compile(r"\bST\b"), "Single Target"),
    ("Physical Attack", re.compile(r"\bPhysical (?:Attack|ATK)\b", re.I), "P.ATK"),
    ("Magic Attack", re.compile(r"\bMagic (?:Attack|ATK)\b", re.I), "M.ATK"),
    ("PATK", re.compile(r"(?<![.A-Za-z])PATK(?![.A-Za-z])", re.I), "P.ATK"),
    ("MATK", re.compile(r"(?<![.A-Za-z])MATK(?![.A-Za-z])", re.I), "M.ATK"),
    ("PDEF", re.compile(r"(?<![.A-Za-z])PDEF(?![.A-Za-z])", re.I), "P.DEF"),
    ("MDEF", re.compile(r"(?<![.A-Za-z])MDEF(?![.A-Za-z])", re.I), "M.DEF"),
    ("FLEE", re.compile(r"\bFLEE\b"), "Flee"),
    (
        "Thai P.ATK",
        re.compile(
            r"(?:พลัง|ค่า)โจมตี(?:ทาง)?กายภาพ|"
            r"(?:พลัง)?ATK (?:ทาง)?กายภาพ"
        ),
        "P.ATK",
    ),
    (
        "Thai M.ATK",
        re.compile(
            r"(?:พลัง|ค่า)โจมตี(?:ทาง)?เวท(?:ย์|มนตร์|ย์มนตร์)?|"
            r"(?:พลัง)?ATK (?:ทาง)?เวท(?:ย์|มนตร์|ย์มนตร์)?"
        ),
        "M.ATK",
    ),
    (
        "Thai P.DMG",
        re.compile(r"ความเสียหาย(?:ทาง)?กายภาพ"),
        "P.DMG",
    ),
    (
        "Thai M.DMG",
        re.compile(r"ความเสียหาย(?:ทาง)?(?:เวท|เวทย์|เวทมนตร์|เวทย์มนตร์)"),
        "M.DMG",
    ),
    ("Thai ASPD", re.compile(r"ความเร็วในการโจมตี"), "ASPD"),
    ("Thai MSPD", re.compile(r"ความเร็วในการเคลื่อนที่"), "MSPD"),
    ("Thai Cooldown", re.compile(r"คูลดาวน์", re.I), "CD"),
]


def encode_translation_field(text: str) -> str:
    return (
        text.replace("\\", "\\\\")
        .replace("=", r"\=")
        .replace("//", r"\u002F\u002F")
        .replace("%3D", r"\u00253D")
        .replace("\r", r"\r")
        .replace("\n", r"\n")
    )


def normalize_segment(text: str, counts: Counter[str]) -> str:
    for name, pattern, replacement in RULES:
        text, changed = pattern.subn(replacement, text)
        counts[name] += changed
    return text


def normalize_target(text: str, counts: Counter[str]) -> str:
    parts = PROTECTED_NAME.split(text)
    for index in range(0, len(parts), 2):
        parts[index] = normalize_segment(parts[index], counts)
    text = "".join(parts)
    text, changed = re.subn(
        r"(?:【\s*([^】\r\n]+?)\s*】|\[\s*([^\]\r\n]+?)\s*\])",
        lambda match: f"[ {(match.group(1) or match.group(2)).strip()} ]",
        text,
    )
    counts["Named brackets"] += changed
    return text


def read_allowed_texts() -> set[str]:
    allowed: set[str] = set()
    with LANGUAGE_KV.open(encoding="utf-8-sig", newline="") as handle:
        for row in csv.reader(handle, delimiter="\t"):
            if len(row) >= 2 and row[0].startswith(ALLOWED_PREFIXES):
                allowed.add(row[1])
    return allowed


def write_preserving_bom(path: Path, text: str, had_bom: bool) -> None:
    data = text.encode("utf-8")
    path.write_bytes((b"\xef\xbb\xbf" if had_bom else b"") + data)


def update_workspace() -> tuple[dict[str, tuple[str, str]], Counter[str]]:
    allowed = read_allowed_texts()
    changes: dict[str, tuple[str, str]] = {}
    counts: Counter[str] = Counter()
    for path in sorted(SPLIT.glob("part_*.tsv")):
        raw = path.read_bytes()
        had_bom = raw.startswith(b"\xef\xbb\xbf")
        text = raw.decode("utf-8-sig")
        lines = text.splitlines(keepends=True)
        output = [lines[0]]
        for raw_line in lines[1:]:
            ending = "\r\n" if raw_line.endswith("\r\n") else "\n" if raw_line.endswith("\n") else ""
            body = raw_line[: -len(ending)] if ending else raw_line
            row = next(csv.reader([body], delimiter="\t"))
            if len(row) < 3:
                output.append(raw_line)
                continue
            index, source, old = row[0], row[1], row[2]
            if source == "ST":
                new = "Single Target"
            elif source == FALCON_CONCENTRATION:
                new = FALCON_CONCENTRATION_TH
            elif source == MALFORMED_POISONED:
                new = MALFORMED_POISONED_TH
            elif source in allowed:
                new = normalize_target(old, counts)
            else:
                output.append(raw_line)
                continue
            if new == old:
                output.append(raw_line)
                continue
            buffer = io.StringIO()
            csv.writer(buffer, delimiter="\t", lineterminator=ending or "\n").writerow(
                [index, source, new]
            )
            output.append(buffer.getvalue())
            changes[source] = (old, new)
        write_preserving_bom(path, "".join(output), had_bom)
    return changes, counts


def update_overrides(changes: dict[str, tuple[str, str]]) -> int:
    raw = OVERRIDES.read_bytes()
    had_bom = raw.startswith(b"\xef\xbb\xbf")
    text = raw.decode("utf-8-sig")
    changed = 0
    for source, (old, new) in changes.items():
        needle = "\t" + source + "\t" + old
        occurrences = text.count(needle)
        if occurrences:
            text = text.replace(needle, "\t" + source + "\t" + new)
            changed += occurrences
    for localization_id in ("10100000143", "10740000002"):
        row = f"{localization_id}\tST\tSingle Target"
        if row not in text:
            text = text.rstrip("\r\n") + "\n" + row + "\n"
            changed += 1
    write_preserving_bom(OVERRIDES, text, had_bom)
    return changed


def rebuild_xunity(path: Path) -> int:
    raw = path.read_bytes()
    had_bom = raw.startswith(b"\xef\xbb\xbf")
    existing = raw.decode("utf-8-sig").splitlines()
    header = existing[:4]
    translations: dict[str, str] = {}
    for split_path in sorted(SPLIT.glob("part_*.tsv")):
        with split_path.open(encoding="utf-8-sig", newline="") as handle:
            for row in csv.DictReader(handle, delimiter="\t"):
                source = row["English"]
                target = row["Thai_Translation"]
                if target and target != source:
                    translations[source] = target
    lines = header + [
        encode_translation_field(source.replace(r"\n", "\n"))
        + "="
        + encode_translation_field(target.replace(r"\n", "\n"))
        for source, target in sorted(translations.items())
    ]
    write_preserving_bom(path, "\n".join(lines) + "\n", had_bom)
    return len(translations)


def main() -> int:
    changes, counts = update_workspace()
    override_rows = update_overrides(changes)
    canonical_rows = rebuild_xunity(CANON)
    auto_rows = rebuild_xunity(AUTO)
    print(f"Normalized workspace rows: {len(changes)}")
    for name, count in counts.items():
        if count:
            print(f"  {name}: {count}")
    print(f"Runtime rows: overrides={override_rows}, canonical={canonical_rows}, auto={auto_rows}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())