#!/usr/bin/env python3
"""Validate the description-only Thai localization policy."""
from __future__ import annotations
from collections import Counter
from pathlib import Path
import csv
import json
import re

ROOT = Path(__file__).resolve().parents[1]
TEXT = ROOT / "Client/BepInEx/Translation/ja/Text"
CANON = TEXT / "RO3_CanonicalTranslations.txt"
AUTO = TEXT / "_AutoGeneratedTranslations.txt"
PRIORITY = TEXT / "RO3_PriorityOverrides.txt"
RUNTIME = TEXT / "RO3_RuntimePlaceholders.txt"
OVERRIDES = ROOT / "Client/BepInEx/config/RO3.LocalizationOverrides.tsv"
ALIASES = ROOT / "Client/BepInEx/config/RO3.LocalizationAliases.tsv"
LANGUAGE_KV = ROOT / "_TranslationWorkspace/LanguageKV_full_en.tsv"
SPLIT = ROOT / "_TranslationWorkspace/split_1000"
ALLOWED_PREFIXES = (
    "101103",  # skill descriptions
    "102203",  # skill/buff effect descriptions
    "108001",  # suggested skill-effect descriptions
    "123901",  # item descriptions
    "100501",  # consumable/food descriptions
    "131500",  # quest objectives
    "131502",  # quest descriptions
    "131506",  # active quest objectives
)
TOKEN = re.compile(r"\$\{[^}\r\n]+\}|@\{[^}\r\n]+\}|\\u[0-9A-Fa-f]{4}|\\[nrt]")
STYLE_TOKEN = re.compile(r"\^\{[^}\r\n]+\}")
BRACKET_TOKEN = re.compile(r"(?:\[|【)[^\]】\r\n]+(?:\]|】)")
BARE_NUMBER_BRACE = re.compile(r"(?<![$@^])\{\d+\}")
UP_ARROW_MARKER = re.compile(r"↑\{\d+\}")
THAI = re.compile(r"[\u0E00-\u0E7F]")
SOURCE_BRACKET = re.compile(r"(?:\[|【)([^\]】\r\n]+)(?:\]|】)")
PLAIN_ENGLISH_BRACKET_NAME = re.compile(r"^[A-Za-z][A-Za-z0-9 .,'’&+:/()\-]*$")
TECHNICAL_TERMS = ("STR", "AGI", "VIT", "INT", "DEX", "LUK")
UNSAFE_STANDALONE = re.compile(r"^(?:DMG Bonus|(?:STR|AGI|VIT|INT|DEX|LUK)\s*\+[^A-Za-z]*\.?)$")


def split_xunity(line: str) -> tuple[str, str] | None:
    for index, char in enumerate(line):
        if char != "=":
            continue
        slash_count = 0
        cursor = index - 1
        while cursor >= 0 and line[cursor] == "\\":
            slash_count += 1
            cursor -= 1
        if slash_count % 2 == 0:
            return line[:index], line[index + 1 :]
    return None


def load_dictionary(path: Path) -> list[tuple[str, str]]:
    rows = []
    for number, raw in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
        if not raw or raw.startswith("//"):
            continue
        pair = split_xunity(raw)
        if pair is None or not pair[0] or not pair[1]:
            raise SystemExit(f"{path}:{number}: malformed translation row")
        rows.append(pair)
    return rows


def load_tsv(path: Path) -> list[tuple[str, str, str]]:
    rows = []
    for number, raw in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
        if not raw or raw.startswith("#"):
            continue
        parts = raw.split("\t", 2)
        if len(parts) != 3 or not all(parts):
            raise SystemExit(f"{path}:{number}: malformed TSV row")
        rows.append((parts[0], parts[1], parts[2]))
    return rows


def check_tokens(label: str, rows: list[tuple[str, str]]) -> None:
    failures = []
    for source, target in rows:
        if Counter(TOKEN.findall(source)) != Counter(TOKEN.findall(target)):
            failures.append((source, target))
            if len(failures) == 10:
                break
    if failures:
        raise SystemExit(label + ": placeholder mismatch\n" + "\n".join(f"  {s!r} -> {t!r}" for s, t in failures))


def check_format_integrity(label: str, rows: list[tuple[str, str]]) -> None:
    failures = []
    for source, target in rows:
        source_style = STYLE_TOKEN.findall(source)
        target_style = STYLE_TOKEN.findall(target)
        source_brackets = BRACKET_TOKEN.findall(source)
        target_brackets = BRACKET_TOKEN.findall(target)
        source_stray_carets = STYLE_TOKEN.sub("", source).count("^")
        target_stray_carets = STYLE_TOKEN.sub("", target).count("^")
        delimiters_match = all(source.count(char) == target.count(char) for char in "[]【】")
        if (
            source_style != target_style
            or source_brackets != target_brackets
            or Counter(BARE_NUMBER_BRACE.findall(source)) != Counter(BARE_NUMBER_BRACE.findall(target))
            or source_stray_carets != target_stray_carets
            or UP_ARROW_MARKER.search(target)
            or not delimiters_match
        ):
            failures.append((source, target))
            if len(failures) == 10:
                break
    if failures:
        raise SystemExit(label + ": formatting marker mismatch\n" + "\n".join(f"  {s!r} -> {t!r}" for s, t in failures))


def check_terms_and_names(label: str, rows: list[tuple[str, str]]) -> None:
    failures = []
    for source, target in rows:
        expected = [x for x in SOURCE_BRACKET.findall(source) if PLAIN_ENGLISH_BRACKET_NAME.fullmatch(x)]
        expected += [term for term in TECHNICAL_TERMS if re.search(rf"(?<![A-Za-z]){re.escape(term)}(?![A-Za-z])", source)]
        missing = [value for value in dict.fromkeys(expected) if value not in target]
        if missing:
            failures.append((source, target, missing))
            if len(failures) == 10:
                break
    if failures:
        raise SystemExit(label + ": English name/technical term missing\n" + "\n".join(f"  missing {m!r}: {s!r} -> {t!r}" for s, t, m in failures))

language_kv = {}
for raw in LANGUAGE_KV.read_text(encoding="utf-8-sig").splitlines():
    if "\t" in raw:
        localization_id, english = raw.split("\t", 1)
        language_kv[localization_id] = english
allowed_ids = {key for key in language_kv if key.startswith(ALLOWED_PREFIXES)}
allowed_texts = {language_kv[key] for key in allowed_ids}
canonical = load_dictionary(CANON)
auto = load_dictionary(AUTO)
overrides = load_tsv(OVERRIDES)
aliases = load_tsv(ALIASES)
priority = load_dictionary(PRIORITY)
runtime = load_dictionary(RUNTIME)
if canonical != auto:
    raise SystemExit("canonical and autogenerated dictionaries differ")
if not (4000 <= len(canonical) <= len(allowed_texts)):
    raise SystemExit(f"unexpected canonical description count: {len(canonical)}")
if any(source not in allowed_texts for source, _ in canonical):
    raise SystemExit("canonical contains text outside the description-only scope")
if any(UNSAFE_STANDALONE.fullmatch(source) and target != source for source, target in canonical):
    raise SystemExit("canonical translates a standalone option/stat label")
if any(localization_id not in allowed_ids for localization_id, _, _ in overrides):
    raise SystemExit("override map contains an ID outside the description-only scope")
if any(UNSAFE_STANDALONE.fullmatch(source) and target != source for _, source, target in overrides):
    raise SystemExit("override map translates a standalone option/stat label")
if priority or runtime:
    raise SystemExit("global priority/regex rules must stay disabled in description-only mode")
check_tokens("canonical", canonical)
check_tokens("overrides", [(source, target) for _, source, target in overrides])
check_format_integrity("canonical", canonical)
check_format_integrity("overrides", [(source, target) for _, source, target in overrides])
check_terms_and_names("canonical", canonical)
check_terms_and_names("overrides", [(source, target) for _, source, target in overrides])
thai_targets = sum(bool(THAI.search(target)) for _, target in canonical)
if thai_targets < 3500:
    raise SystemExit(f"only {thai_targets} scoped descriptions contain Thai text")
# Aliases are retained only to normalize non-English source names to English.
if any(THAI.search(target) for _, _, target in aliases):
    raise SystemExit("an alias target is still Thai; names must normalize to English")
description_aliases = [row for row in aliases if row[0].startswith(ALLOWED_PREFIXES)]
if len(description_aliases) < 1000:
    raise SystemExit(f"too few Chinese description aliases: {len(description_aliases)}")
description_source = json.loads((ROOT / "_TranslationWorkspace/description_aliases.json").read_text(encoding="utf-8"))
english_by_id = {row[0]: row[1] for row in description_source["rows"]}
for localization_id, source, target in description_aliases:
    if target != english_by_id.get(localization_id):
        raise SystemExit(f"description alias does not resolve to its English ID value: {localization_id}")
    if sum("\u3400" <= char <= "\u9fff" for char in source) < 6:
        raise SystemExit(f"description alias is too short to be prose: {localization_id}: {source!r}")
check_tokens("description aliases", [(source, target) for _, source, target in description_aliases])
workspace_rows = 0
workspace_failures = []
workspace_pairs = []
for path in sorted(SPLIT.glob("part_*.tsv")):
    with path.open(encoding="utf-8-sig", newline="") as handle:
        for row in csv.DictReader(handle, delimiter="\t"):
            workspace_rows += 1
            english = row["English"]
            target = row["Thai_Translation"]
            workspace_pairs.append((english, target))
            if (english not in allowed_texts or UNSAFE_STANDALONE.fullmatch(english)) and target != english:
                workspace_failures.append((path.name, english, target))
                if len(workspace_failures) == 10:
                    break
    if workspace_failures:
        break
if workspace_rows != 26615:
    raise SystemExit(f"workspace row count is {workspace_rows}, expected 26615")
if workspace_failures:
    raise SystemExit("workspace translates text outside description scope:\n" + "\n".join(f"  {p}: {s!r} -> {t!r}" for p, s, t in workspace_failures))
check_tokens("workspace", workspace_pairs)
check_format_integrity("workspace", workspace_pairs)
print(f"Description-only Thai payload OK: canonical={len(canonical)}, overrides={len(overrides)}, aliases={len(aliases)}, English Chinese-description aliases={len(description_aliases)}, Thai descriptions={thai_targets}, workspace={workspace_rows}")
