#!/usr/bin/env python3
"""Validate the tracked Thai localization payload without rebuilding the legacy patcher."""
from __future__ import annotations
from collections import Counter
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
CANON = ROOT / "Client/BepInEx/Translation/ja/Text/RO3_CanonicalTranslations.txt"
AUTO = ROOT / "Client/BepInEx/Translation/ja/Text/_AutoGeneratedTranslations.txt"
OVERRIDES = ROOT / "Client/BepInEx/config/RO3.LocalizationOverrides.tsv"
ALIASES = ROOT / "Client/BepInEx/config/RO3.LocalizationAliases.tsv"
TOKEN = re.compile(r"\$\{[^}\r\n]+\}|@\{[^}\r\n]+\}|\\u[0-9A-Fa-f]{4}|\\[nrt]")
THAI = re.compile(r"[\u0E00-\u0E7F]")


def split_xunity(line: str) -> tuple[str, str] | None:
    for index, char in enumerate(line):
        if char != "=":
            continue
        slash_count = 0
        cursor = index - 1
        while cursor >= 0 and line[cursor] == "\\":
            slash_count += 1
            cursor -= 1
        if slash_count % 2 == 0:
            return line[:index], line[index + 1 :]
    return None


def load_dictionary(path: Path) -> list[tuple[str, str]]:
    rows = []
    for number, raw in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
        if not raw or raw.startswith("//"):
            continue
        pair = split_xunity(raw)
        if pair is None or not pair[0] or not pair[1]:
            raise SystemExit(f"{path}:{number}: malformed translation row")
        rows.append(pair)
    return rows


def load_tsv(path: Path) -> list[tuple[str, str, str]]:
    rows = []
    for number, raw in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
        if not raw or raw.startswith("#"):
            continue
        parts = raw.split("\t", 2)
        if len(parts) != 3 or not all(parts):
            raise SystemExit(f"{path}:{number}: malformed TSV row")
        rows.append((parts[0], parts[1], parts[2]))
    return rows


def check_tokens(label: str, rows: list[tuple[str, str]]) -> None:
    failures = []
    for source, target in rows:
        if Counter(TOKEN.findall(source)) != Counter(TOKEN.findall(target)):
            failures.append((source, target))
            if len(failures) == 10:
                break
    if failures:
        samples = "\n".join(f"  {s!r} -> {t!r}" for s, t in failures)
        raise SystemExit(f"{label}: placeholder mismatch\n{samples}")


canonical = load_dictionary(CANON)
auto = load_dictionary(AUTO)
overrides = load_tsv(OVERRIDES)
aliases = load_tsv(ALIASES)
if len(canonical) != 26615:
    raise SystemExit(f"canonical row count is {len(canonical)}, expected 26615")
if canonical != auto:
    raise SystemExit("canonical and autogenerated dictionaries differ")
if len(overrides) < 17000 or len(aliases) < 8500:
    raise SystemExit("runtime TSV payload is unexpectedly small")
check_tokens("canonical", canonical)
check_tokens("overrides", [(source, target) for _, source, target in overrides])
thai_targets = sum(bool(THAI.search(target)) for _, target in canonical)
if thai_targets < 20000:
    raise SystemExit(f"only {thai_targets} canonical targets contain Thai text")
print(f"Thai payload OK: canonical={len(canonical)}, overrides={len(overrides)}, aliases={len(aliases)}, Thai targets={thai_targets}")
