#!/usr/bin/env python3
"""Validate the tracked Thai localization payload without rebuilding the legacy patcher."""
from __future__ import annotations
from collections import Counter
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
CANON = ROOT / "Client/BepInEx/Translation/ja/Text/RO3_CanonicalTranslations.txt"
AUTO = ROOT / "Client/BepInEx/Translation/ja/Text/_AutoGeneratedTranslations.txt"
PRIORITY = ROOT / "Client/BepInEx/Translation/ja/Text/RO3_PriorityOverrides.txt"
RUNTIME = ROOT / "Client/BepInEx/Translation/ja/Text/RO3_RuntimePlaceholders.txt"
OVERRIDES = ROOT / "Client/BepInEx/config/RO3.LocalizationOverrides.tsv"
ALIASES = ROOT / "Client/BepInEx/config/RO3.LocalizationAliases.tsv"
LANGUAGE_KV = ROOT / "_TranslationWorkspace/LanguageKV_full_en.tsv"
TOKEN = re.compile(r"\$\{[^}\r\n]+\}|@\{[^}\r\n]+\}|\\u[0-9A-Fa-f]{4}|\\[nrt]")
THAI = re.compile(r"[\u0E00-\u0E7F]")
SOURCE_BRACKET = re.compile(r"(?:\[|【)([^\]】\r\n]+)(?:\]|】)")
PLAIN_ENGLISH_BRACKET_NAME = re.compile(r"^[A-Za-z][A-Za-z0-9 .,'’&+:/()\-]*$")
ENGLISH_NAME_PREFIXES = (
    "100800",  # maps and scenes
    "106801",  # maps and instances
    "104700",  # NPCs/world entities
    "105300",  # monsters
    "123900",  # items
    "104500",  # pets
    "128600",  # pets
    "101102",  # skills
    "117700",  # auto-battle skill names
)


def split_xunity(line: str) -> tuple[str, str] | None:
    for index, char in enumerate(line):
        if char != "=":
            continue
        slash_count = 0
        cursor = index - 1
        while cursor >= 0 and line[cursor] == "\\":
            slash_count += 1
            cursor -= 1
        if slash_count % 2 == 0:
            return line[:index], line[index + 1 :]
    return None


def load_dictionary(path: Path) -> list[tuple[str, str]]:
    rows = []
    for number, raw in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
        if not raw or raw.startswith("//"):
            continue
        pair = split_xunity(raw)
        if pair is None or not pair[0] or not pair[1]:
            raise SystemExit(f"{path}:{number}: malformed translation row")
        rows.append(pair)
    return rows


def load_tsv(path: Path) -> list[tuple[str, str, str]]:
    rows = []
    for number, raw in enumerate(path.read_text(encoding="utf-8-sig").splitlines(), 1):
        if not raw or raw.startswith("#"):
            continue
        parts = raw.split("\t", 2)
        if len(parts) != 3 or not all(parts):
            raise SystemExit(f"{path}:{number}: malformed TSV row")
        rows.append((parts[0], parts[1], parts[2]))
    return rows


def check_tokens(label: str, rows: list[tuple[str, str]]) -> None:
    failures = []
    for source, target in rows:
        if Counter(TOKEN.findall(source)) != Counter(TOKEN.findall(target)):
            failures.append((source, target))
            if len(failures) == 10:
                break
    if failures:
        samples = "\n".join(f"  {s!r} -> {t!r}" for s, t in failures)
        raise SystemExit(f"{label}: placeholder mismatch\n{samples}")


def check_bracketed_names(label: str, rows: list[tuple[str, str]]) -> None:
    failures = []
    for source, target in rows:
        expected = []
        for value in SOURCE_BRACKET.findall(source):
            if PLAIN_ENGLISH_BRACKET_NAME.fullmatch(value) and value not in expected:
                expected.append(value)
        missing = [value for value in expected if value not in target]
        if missing:
            failures.append((source, target, missing))
            if len(failures) == 10:
                break
    if failures:
        samples = "\n".join(
            f"  missing {missing!r}: {source!r} -> {target!r}"
            for source, target, missing in failures
        )
        raise SystemExit(f"{label}: English bracketed name missing\n{samples}")


canonical = load_dictionary(CANON)
auto = load_dictionary(AUTO)
priority = load_dictionary(PRIORITY)
runtime = load_dictionary(RUNTIME)
overrides = load_tsv(OVERRIDES)
aliases = load_tsv(ALIASES)
language_kv = {}
for raw in LANGUAGE_KV.read_text(encoding="utf-8-sig").splitlines():
    if "\t" not in raw:
        continue
    localization_id, english = raw.split("\t", 1)
    language_kv[localization_id] = english
protected_names = {
    english
    for localization_id, english in language_kv.items()
    if localization_id.startswith(ENGLISH_NAME_PREFIXES)
}
if len(canonical) != 26615:
    raise SystemExit(f"canonical row count is {len(canonical)}, expected 26615")
if canonical != auto:
    raise SystemExit("canonical and autogenerated dictionaries differ")
if len(overrides) < 17000 or len(aliases) < 8500:
    raise SystemExit("runtime TSV payload is unexpectedly small")
check_tokens("canonical", canonical)
check_tokens("overrides", [(source, target) for _, source, target in overrides])
check_bracketed_names("canonical", canonical)
check_bracketed_names("autogenerated", auto)
check_bracketed_names("priority", priority)
check_bracketed_names("runtime", runtime)
check_bracketed_names("overrides", [(source, target) for _, source, target in overrides])
thai_targets = sum(bool(THAI.search(target)) for _, target in canonical)
if thai_targets < 20000:
    raise SystemExit(f"only {thai_targets} canonical targets contain Thai text")
canonical_map = dict(canonical)
wrong_canonical_names = [
    (english, canonical_map.get(english))
    for english in sorted(protected_names)
    if canonical_map.get(english) != english
]
if wrong_canonical_names:
    raise SystemExit(
        "protected names were translated in canonical dictionary:\n"
        + "\n".join(f"  {source!r} -> {target!r}" for source, target in wrong_canonical_names[:20])
    )
wrong_overrides = [
    (localization_id, english, target)
    for localization_id, english, target in overrides
    if (
        localization_id.startswith(ENGLISH_NAME_PREFIXES)
        or english in protected_names
    )
    and target != english
]
if wrong_overrides:
    raise SystemExit(
        "protected names were translated in localization overrides:\n"
        + "\n".join(
            f"  {localization_id}: {english!r} -> {target!r}"
            for localization_id, english, target in wrong_overrides[:20]
        )
    )
wrong_aliases = [
    (localization_id, source, target, language_kv.get(localization_id))
    for localization_id, source, target in aliases
    if localization_id.startswith(ENGLISH_NAME_PREFIXES)
    and target != language_kv.get(localization_id)
]
if wrong_aliases:
    raise SystemExit(
        "protected aliases do not normalize to English:\n"
        + "\n".join(
            f"  {localization_id}: {source!r} -> {target!r}; expected {expected!r}"
            for localization_id, source, target, expected in wrong_aliases[:20]
        )
    )
print(
    f"Thai payload OK: canonical={len(canonical)}, overrides={len(overrides)}, "
    f"aliases={len(aliases)}, Thai targets={thai_targets}, "
    f"English protected names={len(protected_names)}"
)
