"""Read-only verification of the installed display patch and bounded live evidence."""
import argparse
import hashlib
import json
import re
from pathlib import Path

repo = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--backup', type=Path, required=True)
parser.add_argument('--version', required=True)
parser.add_argument('--official-update', type=Path,
                    help='Explicitly reviewed before/after hashes for a launcher-applied manifest update; never updates a baseline automatically.')
options = parser.parse_args()
client = repo.parent / 'Client'
audit = json.loads((options.backup / 'audit.json').read_text(encoding='utf-8-sig'))


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest().upper()


failures = []
official_transition = {}
if options.official_update:
    transition = json.loads(options.official_update.read_text(encoding='utf-8-sig'))
    allowed = {'ro3_Data/StreamingAssets/Recovery/recovery-compatibility-manifest.json',
               'ro3_Data/StreamingAssets/Recovery/recovery-compatibility-manifest.json.sig'}
    files = transition.get('files', {})
    if set(files) != allowed or not transition.get('evidence'):
        raise SystemExit('Official update record must pin the manifest and signature, with reviewed evidence.')
    protected = {key.replace('\\', '/'): value.upper() for key, value in audit['protected_sha256'].items()}
    for relative, values in files.items():
        before = values.get('before', '').upper()
        after = values.get('after', '').upper()
        # A later patch deployment may already use the reviewed official update
        # as its baseline; neither case authorizes a different installed hash.
        if not re.fullmatch('[0-9A-F]{64}', before) or protected.get(relative) not in (before, after):
            raise SystemExit('Official update is not chained to this deployment: ' + relative)
        if not re.fullmatch('[0-9A-F]{64}', after) or sha(client / relative) != after:
            raise SystemExit('Official update hash differs: ' + relative)
        official_transition[relative] = after
matching_payload = 0
cache_append_bytes = 0
for relative in audit['payload']:
    source = repo / 'Client' / relative
    installed = client / relative
    if sha(source) == sha(installed):
        matching_payload += 1
    elif relative.endswith('_AutoGeneratedTranslations.txt') and installed.read_bytes().startswith(source.read_bytes()):
        # XUnity can persist cache hits during play. Accept only append-only
        # growth; changes to any deployed prefix remain a verification failure.
        cache_append_bytes = installed.stat().st_size - source.stat().st_size
    else:
        failures.append('Payload differs: ' + relative)
for relative, expected in audit['protected_sha256'].items():
    expected = official_transition.get(relative.replace('\\', '/'), expected)
    if sha(client / relative) != expected.upper():
        failures.append('Protected file differs: ' + relative)

originals = 0
superseded_originals = 0
recovery = client / 'ro3_Data/StreamingAssets/Recovery'
for relative in ('recovery-compatibility-manifest.json', 'LuaPayload/Localization_en.lua.bytes',
                 'LuaPayload/Localization_zh_CN.lua.bytes', 'LuaPayload/Localization_zh_TW.lua.bytes'):
    path = recovery / relative
    official_relative = 'ro3_Data/StreamingAssets/Recovery/' + relative
    if official_relative in official_transition:
        # An official update supersedes the old restore copy. Keep it intact;
        # compare the installed manifest with the explicitly pinned new hash.
        original_path = Path(str(path) + '.ro3-ja-original')
        if not original_path.is_file() or sha(original_path) != files[official_relative]['before'].upper():
            failures.append('Superseded original backup differs or is missing: ' + relative)
        else:
            superseded_originals += 1
        continue
    if sha(path) != sha(Path(str(path) + '.ro3-ja-original')):
        failures.append('Official original differs: ' + relative)
    originals += 1

log = (client / 'BepInEx/LogOutput.log').read_text(encoding='utf-8-sig', errors='replace')
loaded = re.search(r'Loading \[RO3 Localization Table Patcher ([0-9.]+)\]', log)
if not loaded or loaded[1] != options.version:
    failures.append('Expected patch version is not loaded')
regression = re.search(r'\[Regression\] passed=(\d+)/(\d+)', log)
if not regression or regression[1] != regression[2] or int(regression[2]) != audit['live_cases']:
    failures.append('Live regression checks are absent or failing')
if re.search(r'\[Display\].*(?:failed|Translation skipped)', log, re.IGNORECASE):
    failures.append('Display hook or translation reported a failure')
for required in ('Render text hook installed: TMPro.TMP_Text.ParseInputText',
                 'Render text hook installed: UnityEngine.UI.Text.OnPopulateMesh',
                 'Hook installed: MTextData.', 'Hook installed: TextMeshBuilder.'):
    if required not in log:
        failures.append('Required display path hook absent: ' + required)

# Report aggregate behavior only. Never export names, chat bodies, character IDs,
# or recruitment link identifiers from the user's game log.
categories = {
    'reward-popup': ('恭喜获得', '恭喜獲得', 'Congrats on Obtaining'),
    'item-share': ('Discover a great item! Come check it out!', 'Mink Coat'),
    'resonance': ('For every ', 'Song of Suffering'),
    'equipment': ('JobRestriction:', 'Job Restriction:', 'Job Restriction：'),
    'pickup': ('Minted Coin', 'Sharp Scale'),
    'stall-item': ('紅辣椒', '紅色藥草', '红辣椒', '红色药草'),
    'life-skill-exp': ('Gardener',),
    'commission': ('Defeat Monsters', 'Geffen Outskirts'),
    'world-label': ('吉芬', '下水道', '斐扬', '斐揚', 'Abandoned Village', '虫蛹', '蟲蛹'),
    'recruitment': ('Tap to Join Party',),
    'ranking': ('排行榜',),
    'reward-counter': ('Reward Count',),
    'pet-buff': ('Increases the target',),
    'collection': ('Standard Cards Collected', '筛选当前道具列表', '篩選當前道具列表'),
    'quest-panel': ('Time to Explore Freely', 'end of the current main'),
    'event-notice': ('During the event, each player',),
    'market-stock': ('For Sale:',),
    'trophy': ('Reach Wardrobe', 'Trophies Achieved', 'Appearance ', '一键领取', '一鍵領取'),
    'player-rank': ('ランク:无', 'ランク:無', 'Rank: None', '无', '無'),
    'market-search': ('上架中', '公示中'),
    'party-finder': ('组队平台', '組隊平台', 'party is recruiting'),
    'guild-funds': ('资金榜', '資金榜', '排名', '玩家名称', '职务', '捐赠额度'),
    'soul-core': ('无主灵魂核心', '無主靈魂核心'),
    'guild-league': ('公会人数达到', '公會人數達到', '上周公会活跃', '上週公會活躍', '每赛程首周', '每賽程首週'),
    'echo-tooltip': ('珠泪螺壳', 'Rating ', 'Admonitory Song'),
    'map-gate': ('Prontera North Gate',),
    'event-prefab': ('活动任务', '公会联赛', '领土战争', '自然之神伊尔玛塔'),
    'mail-prefab': ('邮件', '天后过期'),
}
evidence = {name: {'observed': 0, 'translated': 0, 'residual_source': 0} for name in categories}
for line in log.splitlines():
    if '[DisplayTrace]' not in line or ' source=' not in line or ' => ' not in line:
        continue
    source, target = line.split(' source=', 1)[1].split(' => ', 1)
    for name, tokens in categories.items():
        found = [token for token in tokens if token in source]
        if name == 'player-rank':
            found = [token for token in found if token not in ('无', '無') or (
                source == token and '/Team_TTxt/TeamType_TTxt/Layout_Info/Info/Top_GraphicSwitchG/TipsRoot_RTransform ' in line)]
        if not found:
            continue
        evidence[name]['observed'] += 1
        evidence[name]['translated'] += source != target
        evidence[name]['residual_source'] += any(token in target for token in found)

print(json.dumps({
    'loaded_version': loaded[1] if loaded else None,
    'matching_payload_files': matching_payload,
    'autogenerated_cache_append_bytes': cache_append_bytes,
    'protected_files_checked': len(audit['protected_sha256']),
    'official_original_pairs_checked': originals,
    'official_manifest_updates_reviewed': len(official_transition) // 2,
    'superseded_original_backups_preserved': superseded_originals,
    'live_regression': '/'.join(regression.groups()) if regression else None,
    'live_evidence': evidence,
    'failures': failures,
}, indent=2, ensure_ascii=True))
raise SystemExit(bool(failures))
